{"name": "test_resend_verification", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [200]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_resend_verification>\n\n    def test_resend_verification(self):\n        case = self.test_data[\"resend_verification\"][0]\n        response = self.api.resend_verification(email=case[\"email\"])\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [200]> is not an instance of <class 'dict'>\n\nmanagement_user.py:49: AssertionError"}, "start": 1754043680679, "stop": 1754043680840, "uuid": "2eb6ac8f-27de-40a8-93ed-b6f385e5697a", "historyId": "1c64ed79e472e67dcd6d08919caa252a", "testCaseId": "1c64ed79e472e67dcd6d08919caa252a", "fullName": "tests.management_user.TestManagementUserAuth#test_resend_verification", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "17124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}