{"name": "test_verify_email", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [400]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_verify_email>\n\n    def test_verify_email(self):\n        case = self.test_data[\"verify_email\"][0]\n        response = self.api.verify_email(token=case[\"token\"])\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [400]> is not an instance of <class 'dict'>\n\nmanagement_user.py:42: AssertionError"}, "start": 1754043680985, "stop": 1754043681042, "uuid": "d5437e48-088c-473d-be0e-3520764d155a", "historyId": "5dcef521107a554b16339fd9d6c0f954", "testCaseId": "5dcef521107a554b16339fd9d6c0f954", "fullName": "tests.management_user.TestManagementUserAuth#test_verify_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "17124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}