{"uuid": "2976b645-c90a-4ddc-85eb-e7716c929d23", "children": ["30ae36eb-973c-4fc8-85db-2ce96d16a1b1"], "befores": [{"name": "gym_user_id", "status": "failed", "statusDetails": {"message": "Failed: Fetching gym user ID fixture failed: 503 Server Error: Service Unavailable for url: http://localhost:8000/api/v1/gym/user/me\n", "trace": "  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\tests\\conftest.py\", line 133, in gym_user_id\n    pytest.fail(f\"Fetching gym user ID fixture failed: {e}\")\n  File \"C:\\Users\\jothi\\Documents\\api-testing-repo\\.venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754397314103, "stop": 1754397314255}], "start": 1754397314103, "stop": 1754397314467}