{"name": "test_verify_email", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8000/api/v1/management/auth/verify-email?token=bXGW6K0HGRqgiuuVEusXbyPqln8qiJJN6w1LdHiYqq9MVcb3gzMf1VlqDG1I_kh5fgH82PJ0cq6DE1dB9i9BVw", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_verify_email>\n\n    def test_verify_email(self):\n        case = self.test_data[\"verify_email\"][0]\n>       response = self.api.verify_email(token=case[\"token\"])\n\nmanagement_user.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\utils\\api_helper1.py:54: in verify_email\n    return self.get(endpoint, params={\"token\": token})\n..\\utils\\api_client.py:86: in get\n    return self._handle_response(resp)\n..\\utils\\api_client.py:47: in _handle_response\n    response.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [400]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8000/api/v1/management/auth/verify-email?token=bXGW6K0HGRqgiuuVEusXbyPqln8qiJJN6w1LdHiYqq9MVcb3gzMf1VlqDG1I_kh5fgH82PJ0cq6DE1dB9i9BVw\n\n..\\.venv\\lib\\site-packages\\requests\\models.py:1026: HTTPError"}, "attachments": [{"name": "log", "source": "d5e7abce-0288-4f87-be16-e5a0037f420d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "69e65fc0-0577-4fed-9029-eedf79f83d6f-attachment.txt", "type": "text/plain"}], "start": 1754282704555, "stop": 1754282704651, "uuid": "88792236-e454-4b96-8a4b-20551f3b4911", "historyId": "5dcef521107a554b16339fd9d6c0f954", "testCaseId": "5dcef521107a554b16339fd9d6c0f954", "fullName": "tests.management_user.TestManagementUserAuth#test_verify_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "32388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}