{"name": "test_get_current_user", "status": "failed", "statusDetails": {"message": "AssertionError: unexpectedly None", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_get_current_user>\n\n    def test_get_current_user(self):\n>       self.assertIsNotNone(self.access_token)\nE       AssertionError: unexpectedly None\n\nmanagement_user.py:92: AssertionError"}, "start": 1754044030839, "stop": 1754044030839, "uuid": "18a1bd10-8ef7-402b-8507-cb9595a55385", "historyId": "2dd4d846974a139b8a4b2fea14aaee87", "testCaseId": "2dd4d846974a139b8a4b2fea14aaee87", "fullName": "tests.management_user.TestManagementUserAuth#test_get_current_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "12092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}